[package]
name = "sv-filelist-parser"
version = "0.1.0"
authors = ["Raamakrishnan <raamakrishnan1997@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.0"